### ISSUE TITLE
NOT A BUG

### ISSUE THREAD

**Issue by willzyx-hub** [ReVancedTeam/revanced-patcher#18]
Hello guys i see on readme.md you guys asked to add that line pom.xml i wanna to ask how to find pom.xml and add it  ?

**Comment by Lucaskyy** [comment]
What are you trying to do and achieve?

**Comment by Lucaskyy** [comment]
Also, there isn't even a README?
I'm curious, do you have any understanding of GitHub and programming in general?

**Comment by willzyx-hub** [comment]
> Also, there isn't even a README? I'm curious, do you have any understanding of GitHub and programming in general?

I'm quite new about github and i do not know about programming too sorry...

**Comment by oSumAtrIX** [comment]
In that case its fine if you wait until we release proper instructions and documentation for everything, thanks!

**Comment by Lucaskyy** [comment]
> I'm quite new about github and i do not know about programming too sorry...

All good! Like @oSumAtrIX said, please wait for ReVanced to release and then you can use the manager (which uses the patcher behind the scenes) which is meant to be used by users. The patcher is only for developers.
