### ISSUE TITLE
Suggestion: Make a GitLab mirror

### ISSUE THREAD

**Issue by ArjixWasTaken** [ReVancedTeam/revanced-patcher#23]
As discussed on the commit [[03700ffa519e5f20b1a0d0ffe68f3fb504351ee5](https://github.com/ReVancedTeam/revanced-patcher/commit/03700ffa519e5f20b1a0d0ffe68f3fb504351ee5)];

Some stupid company such as google may strike down this repository, and Github will happily comply.

A solution would be to have mirrors on other git sites such as GitLab, <br/> in case Github takes down the repo,  we can simply switch to GitLab as our repo.

Partial idea by: @pc00per

**Comment by oSumAtrIX** [comment]
We already have private mirrors and other people are mirroring the repositories already
