### ISSUE TITLE
bug: `--include` and `--exclude` parameters are ignored

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVancedTeam/revanced-patcher#240]
### Type

Other

### Bug description

It appears the -i and -e parameters are always ignored.

Either include a patch that is normally not included, or exclude a default patch, and neither parameters are followed.

### Steps to reproduce

Patch with exclusive mode, and include at least one patch (such as `swipe-controls`)
The included patch is still excluded:
`INFO: Swipe controls excluded `

Or include a patch that is normally excluded, and it's still excluded:
`INFO: Enable Android debugging excluded`

### Relevant log output

```shell
java -jar revanced-cli-*-all.jar patch --patch-bundle revanced-patches*.jar -m revanced-integrations*.apk --out revanced.apk youtube*.apk --exclusive -i swipe-controls -i enable-android-debugging
INFO: Loading patches 
INFO: Setting patch options 
INFO: Resolving classes using existing cache 
INFO: Decoding app manifest 
INFO: Enable Android debugging excluded 
INFO: Override certificate pinning excluded 
INFO: Change package name excluded 
INFO: Remove screenshot restriction excluded 
INFO: Remove screen capture restriction excluded 
INFO: Spoof Wi-Fi connection excluded 
INFO: Export all activities excluded 
INFO: Predictive back gesture excluded 
INFO: Always autorepeat excluded 
INFO: Vanced MicroG support excluded 
INFO: Enable debugging excluded 
INFO: Minimized playback excluded 
INFO: Open links externally excluded 
INFO: Client spoof excluded 
INFO: Disable zoom haptics excluded 
INFO: Old video quality menu excluded 
INFO: Remember video quality excluded 
INFO: Playback speed excluded 
INFO: HDR auto brightness excluded 
INFO: Video ads excluded 
INFO: Hide ads excluded 
INFO: Hide get premium excluded 
INFO: Wide searchbar excluded 
INFO: Disable auto captions excluded 
INFO: SponsorBlock excluded 
INFO: Enable tablet layout excluded 
INFO: Custom branding excluded 
INFO: Premium heading excluded 
INFO: Hide captions button excluded 
INFO: Hide cast button excluded 
INFO: Navigation buttons excluded 
INFO: Hide autoplay button excluded 
INFO: Hide video action buttons excluded 
INFO: Hide player buttons excluded 
INFO: Disable player popup panels excluded 
INFO: Hide filter bar excluded 
INFO: Hide floating microphone button excluded 
INFO: Comments excluded 
INFO: Hide info cards excluded 
INFO: Hide breaking news shelf excluded 
INFO: Hide layout components excluded 
INFO: Hide seekbar excluded 
INFO: Hide album cards excluded 
INFO: Hide email address excluded 
INFO: Hide timestamp excluded 
INFO: Hide watermark excluded 
INFO: Hide Shorts components excluded 
INFO: Hide crowdfunding box excluded 
INFO: Hide load more button excluded 
INFO: Hide endscreen cards excluded 
INFO: Player flyout menu excluded 
INFO: Theme excluded 
INFO: Spoof app version excluded 
INFO: Disable Shorts on startup excluded 
INFO: Return YouTube Dislike excluded 
INFO: Tablet mini player excluded 
INFO: Alternative thumbnails excluded 
INFO: Remove player controls background excluded 
INFO: Custom player overlay opacity excluded 
INFO: Swipe controls excluded 
INFO: Seekbar tapping excluded 
INFO: Copy video url excluded 
INFO: External downloads excluded 
INFO: Executing patches 
INFO: Compiling modified dex files 
INFO: Aligning youtube_18.32.39.apk 
INFO: Signing youtube_18.32.39.apk
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by aliernfrog** [comment]
This is because CLI no longer uses "some-patch" format: https://github.com/ReVanced/revanced-cli/commit/80a8d88406b2b04d13dca4fb0d7d7d62e1910317

To include/exclude patches now, you need to use the following format:
```
-e "Vanced MicroG support" -i "Custom branding"
```

**Comment by oSumAtrIX** [comment]
The reason the casing is not ignored is because patches can have any name that is a valid string. So if we ignore cases a patch named "A" would also be selected if you try to get exclude or include "a"

**Comment by oSumAtrIX** [comment]
Well, it would be valid, we do not specify any casing constraints

**Comment by oSumAtrIX** [comment]
While I understand the burden, not allowing casing would sound like an unnecessary restriction because it would only be motivated by having to use the correct casing in ReVanced CLI even though ReVanced Patcher or the patches have nothing to with it.

Maybe, for each patch, a GUID can be generated. This way we could avoid name conflicts altogether and the GUID string can be used to select patches.
