### ISSUE TITLE
feat: Incompatible package annotation

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVancedTeam/revanced-patcher#261]
### Type

Functionality

### Issue

Some universal patches fail to work with some apps.  Some of these incompatible apps are well known, such as using change package name with YouTube, yet patching still shows success and the patched app initially appears to work (until the user opens the app settings and it crashes).

### Feature

Add an additional annotation, or additional Patch annotation field, to indicate incompatible apps/versions.  Make it like the existing compatibility field, but for Incompatible apps.

### Motivation

Stop users from applying universal patches that are known not to work correctly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
If a patch is not constrained at all, it is supposed to be compatible with all packages. This means, that if it fails on an app, it is considered to be an issue with the patch, which needs to be fixed. In some scenarios this may be impossible. For example YouTube fails to work after being patched without the MicroG patch, but you can't just blacklist all apps
