### ISSUE TITLE
Optional Signatures members

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVancedTeam/revanced-patcher#9]
The method  `resolveMethod` expects a `Signature`:

https://github.com/ReVancedTeam/revanced-patcher/blob/db7d8f7908b0ede5f952ac0ddd67efe92776c650/src/main/kotlin/net/revanced/patcher/resolver/MethodResolver.kt#L57

Some members should be nullable, in case you certainly know, that these members are not required to resolve a method:
https://github.com/ReVancedTeam/revanced-patcher/blob/db7d8f7908b0ede5f952ac0ddd67efe92776c650/src/main/kotlin/net/revanced/patcher/signature/Signature.kt#L23-L29

In the case of `resolveMethod`, all members should be nullable, except the name.

**Comment by Lucaskyy** [comment]
The reason I am against "nullability" is that that can cause UD and exceptions if not handled properly (which adds extra boilerplate). It would be better to use empty arrays for `opcodes` so in the case something goes haywire it just skips the for-loop instead of crashing full-on.

**Comment by Lucaskyy** [comment]
Sounds good 👍
